# Generated by Django 3.2.8 on 2021-10-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('isbn', models.CharField(max_length=122)),
                ('authors', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
                ('number_of_pages', models.CharField(max_length=122)),
                ('publisher', models.CharField(max_length=122)),
                ('release_date', models.CharField(max_length=122)),
            ],
        ),
    ]
